volumes:
  node_modules:
  vscode_extensions:
  vscode_insiders_extensions:

services:
  # A development container for devs avoiding Visual Studio Code:
  development: &app
    image: vovimayhem/env-vars-js-spa-demo:development
    ports:
      - ${DEMO_WEB_PORT:-3000}:3000
    build: &app_build
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        DEVELOPER_UID: ${UID:-1000}
        DEVELOPER_USERNAME: ${USER:-you}
    command:
      - yarn
      - dev
    volumes:
      # Mount the app code into the app containers:
      - .:/workspaces/env-vars-to-js-spa-demo
      # Replace the container's node_modules with our volume:
      - node_modules:/workspaces/env-vars-to-js-spa-demo/node_modules

    # Keep the stdin open, so we can attach to our app container's process
    # and do things such as byebug, etc:
    stdin_open: true

    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true

    # Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined

    # Specify environment variables available for our app containers. We'll
    # leave a YML anchor in case we need to override or add more variables if
    # needed on each app service:
    environment: &app_environment
      VITE_APP_SALUTE_NAME: ${VITE_APP_SALUTE_NAME:-Francis} # :)
      DEBIAN_FRONTEND: dialog
  
  # The container for us mortal devs using Visual Studio Code:
  devcontainer:
    <<: *app
    
    # I'm removing any port configuration - we'll let Visual Studio Devcontainer
    # to manage those:
    ports: []
    
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    
    volumes:
      - .:/workspaces/env-vars-to-js-spa-demo
      - node_modules:/workspaces/env-vars-to-js-spa-demo/node_modules
      - vscode_extensions:/home/${USER:-you}/.vscode-server/extensions
      - vscode_insiders_extensions:/home/${USER:-you}/.vscode-server-insiders/extensions
    environment:
      <<: *app_environment
      # Use VSCode as editor:
      EDITOR: code -w


  staging:
    image: vovimayhem/env-vars-js-spa-demo:latest
    build:
      <<: *app_build
      target: release
    ports:
      - ${DEMO_WEB_PORT:-3000}:80
    environment:
      VITE_APP_SALUTE_NAME: ${VITE_APP_SALUTE_NAME:-Francis} # :)